version: 0.0.4.{build}
os: Previous Visual Studio 2015
build_script:
- ps: >-
    .\setenv.ps1

    install

    publish -Server AppVeyor -BuildNumber $env:APPVEYOR_BUILD_NUMBER -GitBranch $env:APPVEYOR_REPO_BRANCH
artifacts:
- path: .\artifacts\openrct2.zip
  name: OpenRCT2
