version: 0.0.5.{build}
os: Visual Studio 2015
cache:
- C:\ProgramData\chocolatey\bin -> scripts\ps\appveyor_install.ps1
- C:\ProgramData\chocolatey\lib -> scripts\ps\appveyor_install.ps1
- secure-file -> scripts\ps\appveyor_install.ps1
environment:
  ENCKEY:
    secure: saYAIpqXzpq0U+JH+MNi/isRQ6Y51PZhm4BrnePDiAPptFO5htxFOLegrYqxdy67
  CODE-SIGN-KEY-OPENRCT2.ORG.PFX.PASSWORD:
    secure: bzYmf0ElxisSGyZnIjUOYQ==
  OPENRCT2.ORG_TOKEN:
    secure: leQX3xCQpmBLGuMqrxjFlzexDt96ypNRMM5TTRVHbGE8PwVg9crgeykLc2BIZU6HDHveJCHqh2cGMdHtHYJYcw==
install:
- ps: >-
    .\scripts\ps\appveyor_install.ps1
build_script:
- ps: >-
    .\setenv.ps1

    appveyor_build
artifacts:
- path: .\artifacts\openrct2.zip
  name: OpenRCT2-portable
- path: .\artifacts\*.exe
  name: OpenRCT2-installer
- path: .\artifacts\openrct2-symbols-*.zip
  name: OpenRCT2 debug symbols
